"""
Example Usage of Voyage AI Integration
Demonstrates how to use embeddings and reranking in your application.
"""

from voyage_config import embed_text, embed_texts, rerank_results


def example_single_embedding():
    """Example: Generate a single embedding"""
        print("=" * 50)
            print("Example 1: Single Text Embedding")
                print("=" * 50)

                    text = "Voyage AI provides powerful embeddings for semantic search"
                        embedding = embed_text(text)

                            print(f"Text: {text}")
                                print(f"Embedding dimension: {len(embedding)}")
                                    print(f"First 5 dimensions: {embedding[:5]}")
                                        print()


                                        def example_batch_embeddings():
                                            """Example: Generate embeddings for multiple texts"""
                                                print("=" * 50)
                                                    print("Example 2: Batch Text Embeddings")
                                                        print("=" * 50)

                                                            texts = [
                                                                    "The quick brown fox jumps over the lazy dog",
                                                                            "Machine learning is transforming technology",
                                                                                    "Python is a versatile programming language"
                                                                                        ]

                                                                                            embeddings = embed_texts(texts)

                                                                                                for text, embedding in zip(texts, embeddings):
                                                                                                        print(f"Text: {text}")
                                                                                                                print(f"Embedding dimension: {len(embedding)}")
                                                                                                                        print()
                                                                                                                        
                                                                                                                        
                                                                                                                        def example_reranking():
                                                                                                                            """Example: Rerank documents based on query relevance"""
                                                                                                                                print("=" * 50)
                                                                                                                                    print("Example 3: Document Reranking")
                                                                                                                                        print("=" * 50)
                                                                                                                                        
                                                                                                                                            query = "What is artificial intelligence?"
                                                                                                                                            
                                                                                                                                                documents = [
                                                                                                                                                        "AI is the simulation of human intelligence by machines",
                                                                                                                                                                "The weather today is sunny and warm",
                                                                                                                                                                        "Machine learning is a subset of artificial intelligence",
                                                                                                                                                                                "Python programming guide for beginners",
                                                                                                                                                                                        "Deep learning uses neural networks for pattern recognition"
                                                                                                                                                                                            ]
                                                                                                                                                                                            
                                                                                                                                                                                                reranked = rerank_results(query, documents, top_k=3)
                                                                                                                                                                                                
                                                                                                                                                                                                    print(f"Query: {query}\n")
                                                                                                                                                                                                        print("Top 3 most relevant documents:")
                                                                                                                                                                                                            for i, result in enumerate(reranked, 1):
                                                                                                                                                                                                                    print(f"{i}. Score: {result['relevance_score']:.4f}")
                                                                                                                                                                                                                            print(f"   Document: {result['document']}\n")
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            
                                                                                                                                                                                                                            def example_semantic_search():
                                                                                                                                                                                                                                """Example: Simple semantic search using embeddings"""
                                                                                                                                                                                                                                    print("=" * 50)
                                                                                                                                                                                                                                        print("Example 4: Semantic Search")
                                                                                                                                                                                                                                            print("=" * 50)
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                # Sample documents
                                                                                                                                                                                                                                                    documents = [
                                                                                                                                                                                                                                                            "Cats are independent and enjoy playing with toys",
                                                                                                                                                                                                                                                                    "Dogs are loyal and love to play fetch",
                                                                                                                                                                                                                                                                            "Birds can sing beautiful melodies",
                                                                                                                                                                                                                                                                                    "Python is used for data science and web development",
                                                                                                                                                                                                                                                                                            "JavaScript powers interactive web applications"
                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    # Query
                                                                                                                                                                                                                                                                                                        query = "information about pets"
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            # Get embeddings for all documents and query
                                                                                                                                                                                                                                                                                                                print("Generating embeddings...")
                                                                                                                                                                                                                                                                                                                    query_embedding = embed_text(query)
                                                                                                                                                                                                                                                                                                                        doc_embeddings = embed_texts(documents)
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            # Calculate cosine similarity (simple example)
                                                                                                                                                                                                                                                                                                                                import math
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    def cosine_similarity(vec1, vec2):
                                                                                                                                                                                                                                                                                                                                            dot_product = sum(a * b for a, b in zip(vec1, vec2))
                                                                                                                                                                                                                                                                                                                                                    norm1 = math.sqrt(sum(a ** 2 for a in vec1))
                                                                                                                                                                                                                                                                                                                                                            norm2 = math.sqrt(sum(b ** 2 for b in vec2))
                                                                                                                                                                                                                                                                                                                                                                    return dot_product / (norm1 * norm2) if norm1 * norm2 != 0 else 0
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        # Find most similar documents
                                                                                                                                                                                                                                                                                                                                                                            similarities = [
                                                                                                                                                                                                                                                                                                                                                                                    (cosine_similarity(query_embedding, doc_emb), i, doc)
                                                                                                                                                                                                                                                                                                                                                                                            for i, (doc_emb, doc) in enumerate(zip(doc_embeddings, documents))
                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                    similarities.sort(reverse=True)
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        print(f"\nQuery: {query}\n")
                                                                                                                                                                                                                                                                                                                                                                                                            print("Most relevant documents:")
                                                                                                                                                                                                                                                                                                                                                                                                                for score, idx, doc in similarities[:3]:
                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"Score: {score:.4f} - {doc}")
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n🚀 Voyage AI Integration Examples\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                            # Run examples
                                                                                                                                                                                                                                                                                                                                                                                                                                                    example_single_embedding()
                                                                                                                                                                                                                                                                                                                                                                                                                                                            example_batch_embeddings()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    example_semantic_search()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            example_reranking()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 50)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("✅ All examples completed successfully!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 50)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"❌ Error running examples: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Make sure your VOYAGE_API_KEY is set in your .env file")
